### ISSUE TITLE
No view or template files generated for PowEmailConfirmation

### ISSUE THREAD

**Issue by jagoanmamah** [danschultzer/pow#485] opened 2020-04-10 19:21 UTC
![Screenshot from 2020-04-11 02-15-58](https://user-images.githubusercontent.com/25195185/79017255-17f06800-7b9b-11ea-96df-092729ed7347.png)

**Comment by danschultzer** [comment] 2020-04-10 20:42
Duplicate of #423 

This is to be expected for extensions that doesn't have templates like `PowEmailConfirmation`. I've reworded it in #487 so it's more clear.

**Closed** 2020-04-10 20:45 UTC
Labels: duplicate
