### ISSUE TITLE
pow_extension_routes still defines show for Invitation route though overridden. 

### ISSUE THREAD

**Issue by joshchernoff** [danschultzer/pow#326] opened 2019-11-15 23:45 UTC
Following along with https://hexdocs.pm/pow/pow_invitation.html#limit-invitation-based-on-role

And in regards to overriding routes. 
```
  scope "/", PowInvitation.Phoenix, as: "pow_invitation", do
    pipe_through [:browser, :protected, :admin_role]
    resources "/invitations", InvitationController, only: [:new, :create, :show]
  end
```

I noticed that the show function was still being defined via the `pow_extension_routes` function though it looks to have taken into account the other routes that had been overridden. 

<img width="1408" alt="zsh" src="https://user-images.githubusercontent.com/961877/68983156-94cf0f80-07be-11ea-9db7-b36cad399500.png">

There does seem to be any real harm in this since the first definition of the route end up handling the request. I only posted this because it looked as if all the other overrides had not been duplicated so I assumed this was a bug. I could be wrong.

**Comment by danschultzer** [comment] 2019-11-16 02:14
Yeah, in this case it isn't really an issue, but this is caused by a bug introduced with #292. The routes should be filtered when you override them manually. A fix has been merged to master and it should be working now if you use the master branch. Thanks for letting me know!

**Closed** 2019-11-16 02:14 UTC
